name: Build and publish Python wheels for Windows

on:
  push:
    branches:
      - release

jobs:
  build-wheels:
    name: Build wheels on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: 签出rust代码
        uses: actions/checkout@v2

      - name: 签出前端
        uses: actions/checkout@v2
        with:
          repository: GiantAxeWhy/atomic-bomb-engine-front
          path: vue-project

      - name: 安装Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 构建前端
        run: |
          cd vue-project  
          npm install
          npm run build

      - name: 清空目标路径
        run: Remove-Item -Path python\atomic_bomb_engine\dist\* -Recurse -Force

      - name: 复制dist到Python项目
        run: Copy-Item vue-project/dist/* python\atomic_bomb_engine\dist\ -Recurse

      - name: 设置python环境
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 安装maturin
        run: pip install maturin

      - name: 构建wheels
        run: maturin build --release --interpreter python${{ matrix.python-version }}

      - name: 安装Twine
        run: pip install twine

      - name: 上传wheels到PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ target/wheels/*.whl
